# -*- coding: utf-8 -*-
"""Emotion_Recognition_SFEW2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1I-lgaWLU-dtPyDYp8R2_0pK9n0SSDy-a
"""

from google.colab import drive
drive.mount('/content/drive')

! pip install MTCNN

from mtcnn import MTCNN
import cv2
import os, glob
import numpy as np
# from tqdm import tqdm_notebook
from tqdm.notebook import tqdm_notebook
import shutil
import matplotlib.pyplot as plt
from matplotlib.pyplot import imshow
import keras

pwd

"""UnRara or UnZip in Drive to work on that DataSet"""

!pip install unrar
!unrar x "/content/drive/MyDrive/Datasets/SFEW2.0.rar"

def crop_image(img, detector): 
    data=detector.detect_faces(img)
    biggest=0
    if data !=[]:
        for faces in data:
            box=faces['box']            
            area = box[3]  * box[2]
            if area>biggest:
                biggest=area
                bbox=box 
        bbox[0]= 0 if bbox[0]<0 else bbox[0]
        bbox[1]= 0 if bbox[1]<0 else bbox[1]
        img=img[bbox[1]: bbox[1]+bbox[3],bbox[0]: bbox[0]+ bbox[2]]        
        return (True, img) 
    else:
        return (False, None)

def align_crop_resize(src_list, dest_list, detector, height=None, width= None): 
    success_count=0
    for i,f in tqdm_notebook(enumerate(src_list)):
        dest_dir = os.path.dirname(dest_list[i])
        if not os.path.isdir(dest_dir):
            os.makedirs(dest_dir)
      
        if os.path.isfile(src_list[i]):
            try:
                img=cv2.imread(src_list[i]) 
                shape=img.shape
                  
                cstatus, img=crop_image(img, detector)
                if cstatus:
                    if height != None and width !=None:
                        img=cv2.resize(img, (height, width)) 

                    cv2.imwrite(dest_list[i], img) 
                    success_count +=1
            except:
                print('file ', src_list[i], ' is a bad image file')
    return success_count

detector = MTCNN()
src_list = glob.glob("/content/SFEW2/Train_DataSet_As_Per_Emotion_SFEW2/*/*")
dest_list = [src_list[i].replace("SFEW2", "Cropped_SFEW2") for i in range(len(src_list))] 

align_crop_resize(src_list, dest_list, detector, height=224, width= 224)

!cp -r Cropped_SFEW2 "/content/drive/MyDrive/Datasets"

os.listdir("/content/SFEW2/Train_DataSet_As_Per_Emotion_SFEW2/")

import numpy as np
import tensorflow as tf
from tensorflow import keras

base_model = keras.applications.MobileNetV3Large(
    weights='imagenet',  # Load weights pre-trained on ImageNet.
    input_shape=(224, 224, 3),
    include_top=False,
    classes=7,
    
) 

base_model.trainable = False

inputs = keras.Input(shape=(224, 224, 3))

x = base_model(inputs, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
outputs = keras.layers.Dense(7, activation="softmax")(x)

model = keras.Model(inputs, outputs)

path="/content/Cropped_SFEW2/Train_DataSet_As_Per_Emotion_Cropped_SFEW2"

# dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical")
train_dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical", validation_split=0.3, subset="training", seed=42)
valid_dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical", validation_split=0.3, subset="validation", seed=42)

for i in os.listdir("/content/Cropped_SFEW2/Train_DataSet_As_Per_Emotion_Cropped_SFEW2"):
  print(i,len(os.listdir("/content/Cropped_SFEW2/Train_DataSet_As_Per_Emotion_Cropped_SFEW2/"+i)))

train_dataset.class_names

class_weight={0:1.2,1:3.5,2:2.5,3:1,4:1.3,5:1.22,6:2.5}

model.compile(optimizer=keras.optimizers.Adam(),
              loss="categorical_crossentropy",
              
              metrics=["accuracy"])
# model.fit(dataset, epochs=20, validation_split=0.2)
history = model.fit(train_dataset, epochs=50,class_weight=class_weight, validation_data=valid_dataset)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('MobileNetV2_SFEW2_model_accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.savefig('MobileNetV2_SFEW2_model_accuracy.png')
!cp MobileNetV2_SFEW2_model_accuracy.png "/content/drive/MyDrive/Datasets"
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('MobileNetV2_SFEW2_model_loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.savefig('MobileNetV2_SFEW2_model_loss.png')
!cp MobileNetV2_SFEW2_model_loss.png "/content/drive/MyDrive/Datasets"
plt.show()

print("Training Accuracy ",max(history.history['accuracy']))
print("Testing Accuracy",max(history.history['val_accuracy']))

model.save("mobilenetv2_SFEW2")
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model("mobilenetv2_SFEW2") # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model in the .tflite .
with open('mobilenetv2_SFEW2.tflite', 'wb') as f:
  f.write(tflite_model)

# copy the .tflite to Drive
!cp mobilenetv2_SFEW2.tflite "/content/drive/MyDrive/Datasets"

"""EfficientNetB7 using SFEW2"""

base_model = keras.applications.efficientnet.EfficientNetB7(
    weights = 'imagenet',  # Load weights pre-trained on ImageNet.
    input_shape = (224, 224, 3),
    include_top = False,
    classifier_activation = "softmax",
    classes = 7
) 

base_model.trainable = False

# inputs = keras.Input(shape=(224, 224, 3))
inputs = keras.Input(shape=(224, 224, 3))

x = base_model(inputs, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
outputs = keras.layers.Dense(7, activation="softmax")(x)

model = keras.Model(inputs, outputs)

path="/content/Cropped_SFEW2/Train_DataSet_As_Per_Emotion_Cropped_SFEW2"

# dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical")
train_dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical", validation_split=0.3, subset="training", seed=42)
valid_dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical", validation_split=0.3, subset="validation", seed=42)

model.compile(optimizer=keras.optimizers.Adam(),
              loss="categorical_crossentropy",
              metrics=["accuracy"])
# model.fit(dataset, epochs=20, validation_split=0.2)
history = model.fit(train_dataset, epochs=50, validation_data=valid_dataset)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Inception_SFEW2_model_accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.savefig('Inception_SFEW2_model_accuracy.png')
!cp Inception_SFEW2_model_accuracy.png "/content/drive/MyDrive/Datasets"
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Inception_SFEW2_model_loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.savefig('Inception_SFEW2_model_loss.png')
!cp Inception_SFEW2_model_loss.png "/content/drive/MyDrive/Datasets"
plt.show()

print("Training Accuracy ",max(history.history['accuracy']))
print("Testing Accuracy",max(history.history['val_accuracy']))

model.save("InceptionNet_SFEW2")
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model("InceptionNet_SFEW2") # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model in the .tflite .
with open('InceptionNet_SFEW2.tflite', 'wb') as f:
  f.write(tflite_model)

# copy the .tflite to Drive
!cp InceptionNet_SFEW2.tflite "/content/drive/MyDrive/Datasets"

"""Inception using SFEW2"""

base_model = keras.applications.InceptionV3(
    weights = 'imagenet',  # Load weights pre-trained on ImageNet.
    input_shape = (224, 224, 3),
    include_top = False,
    classifier_activation = "softmax",
    classes = 7
) 

base_model.trainable = False

# inputs = keras.Input(shape=(224, 224, 3))
inputs = keras.Input(shape=(224, 224, 3))

x = base_model(inputs, training=False)
x = keras.layers.GlobalAveragePooling2D()(x)
outputs = keras.layers.Dense(7, activation="softmax")(x)

model = keras.Model(inputs, outputs)

path="/content/drive/MyDrive/Datasets/Cropped_SFEW2/Train_DataSet_As_Per_Emotion_Cropped_SFEW2"

# dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical")
train_dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical", validation_split=0.3, subset="training", seed=42)
valid_dataset = keras.preprocessing.image_dataset_from_directory(path, image_size=(224, 224), label_mode="categorical", validation_split=0.3, subset="validation", seed=42)

model.compile(optimizer=keras.optimizers.Adam(),
              loss="categorical_crossentropy",
              metrics=["accuracy"])
# model.fit(dataset, epochs=20, validation_split=0.2)
history = model.fit(train_dataset, epochs=50, validation_data=valid_dataset)

plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title('Inception_SFEW2_model_accuracy')
plt.ylabel('accuracy')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.savefig('Inception_SFEW2_model_accuracy.png')
!cp Inception_SFEW2_model_accuracy.png "/content/drive/MyDrive/Datasets"
plt.show()

plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('Inception_SFEW2_model_loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'val'], loc='upper left')
plt.savefig('Inception_SFEW2_model_loss.png')
!cp Inception_SFEW2_model_loss.png "/content/drive/MyDrive/Datasets"
plt.show()

print("Training Accuracy ",max(history.history['accuracy']))
print("Testing Accuracy",max(history.history['val_accuracy']))

model.save("InceptionNet_SFEW2")
import tensorflow as tf

# Convert the model
converter = tf.lite.TFLiteConverter.from_saved_model("InceptionNet_SFEW2") # path to the SavedModel directory
tflite_model = converter.convert()

# Save the model in the .tflite .
with open('InceptionNet_SFEW2.tflite', 'wb') as f:
  f.write(tflite_model)

# copy the .tflite to Drive
!cp InceptionNet_SFEW2.tflite "/content/drive/MyDrive/Datasets"

